CREATE TABLE users(
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100),
  username VARCHAR(30),
  password VARCHAR(100),
  register_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE TABLE users(id INT(11) AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),email VARCHAR(100),username VARCHAR(30),password VARCHAR(100),register_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE contacts(
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(30),
  phone_number VARCHAR(11),
  method VARCHAR(10),
  message VARCHAR(300),
  call_message_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- CREATE TABLE contacts(id INT(11) AUTO_INCREMENT PRIMARY KEY,username VARCHAR(30),phone_number VARCHAR(11),method VARCHAR(10),message VARCHAR(300),call_message_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
